$(document).ready(function()
{
    $('#car').mouseover(function()
    {
        $('#chevy').css({
                    'position':'absolute',
                    'left':'0',
                    'transition':'0.5s'
        })
        $('#block').css({
            'position':'absolute',
            'left':'0',
            'transition':'0.5s',
            'box-shadow': '0px 0px 30px 20px rgb(144, 1, 30, 0.7)'
    })
    $('.description').css({'transition':'0.5s',
                            'color':'white'})
})

    $('#car').mouseout(function()
    {
        $('#chevy').css({
                    'position':'absolute',
                    'left':'-25%'
        })
        $('#block').css({
            'position':'absolute',
            'left':'-100%',
            'box-shadow':'none',
            'transition':'0.5s'})
        
            $('.description').css({'transition':'0.5s',
                                'color':'black'})
        })

    $('#car2').mouseover(function()
    {
        $('#chevy2').css({
                    'position':'absolute',
                    'left':'0',
                    'transition':'0.5s'
        })
        $('#block2').css({
            'position':'absolute',
            'left':'0',
            'transition':'0.5s',
            'box-shadow': '0px 0px 30px 20px rgb(255, 165, 0, 0.7)'
        })
})

    $('#car2').mouseout(function()
    {
        $('#chevy2').css({
                    'position':'absolute',
                    'left':'-25%'
        })
        $('#block2').css({
            'position':'absolute',
            'left':'-100%',
            'box-shadow':'none',
            'transition':'0.5s'})
    })
            $('.item-1').click(function()
            {
                $('#glText1').toggle(500)
                $('.item-1').css({
                    'transition':'0.5s'
                })
                $('#glText1').css({
                    'background':'orangered',
                'transition':'0.5s'
                })
        })

    $('.item-2').click(function()
    {
        $('#glText2').toggle(500)
        $('.item-2').css({
            'transition':'0.5s'
        })
        $('#glText2').css({
            'background':'orangered',
        'transition':'0.5s'
        })
    })

        $('.item-3').click(function()
        {
            $('#glText3').toggle(500)
            $('.item-3').css({
                'transition':'0.5s'
            })
            $('#glText3').css({
            'background':'orangered',
            'transition':'0.5s'
            })
        })
})